apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
        - name: {{name}}
          image: {{image}}
          ports:
            - containerPort: {{port}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{name}}
spec:
  selector:
    app: {{name}}
  type: ClusterIP
  ports:
    - port: {{port}}
      protocol: TCP