apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: entry
  annotations:
    kubernetes.io/ingress.class: nginx
    # 不要自动重定向到443
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  backend:
    serviceName: echo
    servicePort: 5100
  rules:
    - http:
        paths:
          - path: /hello
            backend:
              serviceName: hello
              servicePort: 5100
          - path: /echo
            backend:
              serviceName: echo
              servicePort: 5100
---
# nginx配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  # 禁止浏览器自动跳转SSL
  hsts: "false"
  ssl-redirect: "false"