version: '3'
services:
  docker-registry:
    image: "registry"
    restart: unless-stopped
    ports:
      # local only
      - "192.168.99.1:5000:5000"
    volumes:
      - ./registry:/var/lib/registry
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8180:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      # 后续去掉配置在jenkins中
      - /Users/wufeng/.minikube:/Users/wufeng/.minikube
  rancher:
    image: "rancher/rancher"
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./rancher:/var/lib/rancher
